-- ==========================================================
-- AHOLIC WEB STUDIO OS — SCHEMA & MIGRAÇÃO SUPABASE
-- Execute este script no SQL Editor do seu projeto Supabase:
-- https://supabase.com/dashboard/project/_/sql
-- ==========================================================

-- 1. TABELA DE LEADS & CRM
CREATE TABLE IF NOT EXISTS public.leads (
    slug TEXT PRIMARY KEY,
    nome TEXT NOT NULL,
    nicho TEXT,
    cidade TEXT,
    nota NUMERIC(3, 1),
    avaliacoes INTEGER,
    email TEXT,
    telefone TEXT,
    whatsapp TEXT,
    site_antigo TEXT,
    motivo TEXT,
    status TEXT DEFAULT 'novo',
    url_nova TEXT,
    data_proposta DATE,
    valor NUMERIC(10, 2),
    manutencao NUMERIC(10, 2),
    pago INTEGER DEFAULT 0,
    contrato_status TEXT DEFAULT 'pendente',
    contrato_em DATE,
    doc_cliente TEXT,
    end_cliente TEXT,
    obs TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. TABELA DE HISTÓRICO DE VERSÕES DOS SITES
CREATE TABLE IF NOT EXISTS public.versoes_site (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_slug TEXT REFERENCES public.leads(slug) ON DELETE CASCADE,
    numero INTEGER NOT NULL,
    nome_estilo TEXT NOT NULL,
    descricao TEXT,
    arquivo TEXT NOT NULL,
    criado_em TEXT,
    ativo INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. TABELA DE CONFIGURAÇÕES DA AGÊNCIA (AHOLIC)
CREATE TABLE IF NOT EXISTS public.agencia_config (
    id TEXT PRIMARY KEY DEFAULT 'principal',
    razao_social TEXT,
    cpf_cnpj TEXT,
    endereco TEXT,
    cidade_uf TEXT,
    email TEXT,
    whatsapp TEXT,
    hostgator_usuario TEXT,
    hostgator_dominio TEXT,
    hostgator_servidor TEXT,
    hostgator_pasta_base TEXT DEFAULT 'clientes',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. HABILITAR ROW LEVEL SECURITY (RLS)
ALTER TABLE public.leads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.versoes_site ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.agencia_config ENABLE ROW LEVEL SECURITY;

-- POLÍTICAS: Apenas usuários autenticados (você) podem visualizar e gerenciar os dados
CREATE POLICY "Acesso total para usuários autenticados em leads"
ON public.leads FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Acesso total para usuários autenticados em versoes_site"
ON public.versoes_site FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

CREATE POLICY "Acesso total para usuários autenticados em agencia_config"
ON public.agencia_config FOR ALL
TO authenticated
USING (true)
WITH CHECK (true);

-- Permite leitura pública de versões para carregamento de showcase (se desejado)
CREATE POLICY "Leitura pública de versões de sites"
ON public.versoes_site FOR SELECT
TO anon
USING (true);

-- 5. TRIGGER PARA ATUALIZAR O CAMPO updated_at AUTOMATICAMENTE
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = timezone('utc'::text, now());
    RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS update_leads_updated_at ON public.leads;
CREATE TRIGGER update_leads_updated_at
    BEFORE UPDATE ON public.leads
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ==========================================================
-- DADOS INICIAIS (IMPORTAÇÃO DOS SEUS LEADS EXISTENTES)
-- ==========================================================

INSERT INTO public.leads (slug, nome, nicho, cidade, nota, avaliacoes, email, telefone, whatsapp, site_antigo, motivo, status, url_nova, valor, obs)
VALUES
('clinica-anielly-vilela', 'Clínica Anielly Vilela | Estética Avançada', 'Harmonização Facial', 'Caldas Novas', 4.9, 42, '', '(64) 99336-8698', '5564993368698', '', 'Sem site próprio. Atendimento com Ultraformer III e harmonização facial ativo só no Instagram/Maps.', 'redesenhado', 'sites/clinica-anielly-vilela/clinica-anielly-vilela.html', 1500.00, 'Tipo: Do Zero | Rua B28, Qd 36, Itanhangá I'),
('dra-rosana-vecchi', 'Dra. Rosana Vecchi | Rejuvenescimento Facial', 'Harmonização Facial', 'Caldas Novas', 4.8, 38, '', '(62) 98515-0061', '5562985150061', '', 'Sem site próprio. Clínica de alto padrão (Edifício Eleve, Setor Oeste) com procedimentos de alto valor.', 'novo', '', 1800.00, 'Tipo: Do Zero | Endolift, Ultraformer, Fios'),
('dra-anna-clara-junqueira', 'Dra. Anna Clara Junqueira', 'Harmonização Orofacial', 'Caldas Novas', 4.8, 31, '', '(64) 99314-7000', '5564993147000', '', 'Sem site oficial. Presente apenas em diretórios de saúde; sem portal próprio de autoridade.', 'novo', '', 1200.00, 'Tipo: Do Zero | Clínica Mais Saúde, Jardim Roma'),
('quality-odontologia-face', 'Quality Odontologia e Face', 'Harmonização Orofacial', 'Caldas Novas', 4.9, 57, '', '(64) 99271-4048', '5564992714048', 'qualityodontologiaeface.com.br', 'Site atual com layout datado, não otimizado para mobile e sem foco nos procedimentos estéticos.', 'redesenhado', 'sites/quality-odontologia-face/quality-odontologia-face.html', 1500.00, 'Tipo: Redesign | Dra. Silvania Rossi & Dr. Eduardo'),
('top-saude-estetica', 'Top Saúde Estética Facial', 'Harmonização Facial', 'Caldas Novas', 4.7, 45, '', '(64) 3012-4615', '556430124615', 'topsaudeclinicasmedicas.com', 'Site genérico de clínica médica, sem landing page dedicada de alta conversão para estética facial.', 'novo', '', 1200.00, 'Tipo: Redesign / Nova LP | Lipo de papada, bioestimuladores'),
('laura-frares-arquitetura', 'Laura Frares Arquitetura & Interiores', 'Arquitetura & Interiores', 'Rio Verde', 5.0, 28, NULL, NULL, '5564999999999', NULL, 'Criação do Primeiro Site Oficial (Portfólio de Luxo)', 'redesenhado', 'sites/laura-frares-arquitetura/laura-frares-arquitetura.html', 1800.00, 'Foco em condomínio fechado e sedes de fazendas no agro'),
('karla-barros-arquitetura', 'Karla Barros Arquitetura & Interiores', 'Arquitetura & Interiores', 'João Pessoa', 4.9, 26, 'contato@karlabarros.com.br', '(83) 3021-6161', '558330216161', NULL, 'Criação do Primeiro Site Oficial (Foco em orla e alto padrão)', 'redesenhado', 'sites/karla-barros-arquitetura/karla-barros-arquitetura.html', 1900.00, 'Residencial de luxo em Jardim Oceania, Altiplano e Bessa'),
('atipicamente-psi', 'Atipicamente Psi - Núcleo Clínico e Educacional', 'Psicologia & Neurodesenvolvimento', 'Caldas Novas', 5.0, 19, 'contato@atipicamentepsi.com.br', NULL, '5564999999999', NULL, 'Criação do Primeiro Site Oficial (Design Cream + Superdesign)', 'redesenhado', 'sites/atipicamente-psi/atipicamente-psi.html', 1900.00, 'Clínica multidisciplinar com 5 psicólogos (CRP 09), método ABA, TEA e TDAH. Instagram @atipicamentepsi ativo.')
ON CONFLICT (slug) DO NOTHING;

-- VERSÕES DOS SITES
INSERT INTO public.versoes_site (lead_slug, numero, nome_estilo, descricao, arquivo, criado_em, ativo)
VALUES
('atipicamente-psi', 4, 'Editorial Industrial Cream', 'Estilo editorial de alto impacto com tipografia Anton (21vw) + Inter, ruído analógico 4%, seções empilhadas 5rem e botões blur-reveal', 'sites/atipicamente-psi/atipicamente-psi.html', '2026-08-27 11:35', 1),
('atipicamente-psi', 3, 'Fotos Reais Únicas do Google', 'Design Cream com 5 fotos 100% distintas oficiais do Google Maps (fachada, recepção, tenda infantil, consultório e salas)', 'sites/atipicamente-psi/versoes/v3-galeria-fotos-reais-google.html', '2026-08-26 23:25', 0),
('atipicamente-psi', 2, 'Galeria do Interior (Base)', 'Primeira versão com galeria de ambientes e estrutura da clínica', 'sites/atipicamente-psi/versoes/v2-galeria-interior-completa.html', '2026-08-26 23:00', 0),
('atipicamente-psi', 1, 'Design Cream & Superdesign', 'Conceito original cream minimalista com tipografia League Spartan e fotos dos 5 psicólogos', 'sites/atipicamente-psi/versoes/v1-cream-superdesign.html', '2026-08-26 22:45', 0),
('karla-barros-arquitetura', 3, 'Super Travel Luxury', 'Design System Superdesign com tipografia League Spartan, paleta rose/mauve dusty e grid desalinhado', 'sites/karla-barros-arquitetura/karla-barros-arquitetura.html', '2026-08-26 18:46', 1),
('karla-barros-arquitetura', 2, 'Quiet Luxury & CASACOR', 'Alta-costura com fontes Italiana e Cormorant Garamond, paleta champanhe bronze e tela obsidiana', 'sites/karla-barros-arquitetura/versoes/v2-quiet-luxury-italiana.html', '2026-08-26 17:17', 0),
('karla-barros-arquitetura', 1, 'Monografia Minimalista', 'Estilo Studio MK27 com tipografia técnica Space Grotesk e respiro cinza mineral', 'sites/karla-barros-arquitetura/versoes/v1-monografia-editorial.html', '2026-08-26 17:12', 0),
('quality-odontologia-face', 1, 'Swiss Precision & Fotos Reais', 'Identidade clínica com Plus Jakarta Sans, logo original, fotos do Maps e feed do Instagram', 'sites/quality-odontologia-face/quality-odontologia-face.html', '2026-08-26 16:57', 1),
('clinica-anielly-vilela', 1, 'Quiet Luxury Editorial', 'Linho off-white, tipografia Newsreader serifada e foco em procedimentos faciais', 'sites/clinica-anielly-vilela/clinica-anielly-vilela.html', '2026-08-25 22:22', 1),
('laura-frares-arquitetura', 1, 'Monografia Contemporânea', 'Foco em sedes de fazendas e casas de condomínio em Rio Verde (Space Grotesk + JetBrains Mono)', 'sites/laura-frares-arquitetura/laura-frares-arquitetura.html', '2026-08-25 21:12', 1);
